# application.yml
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: barrage-rush-proxy
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: always

# WebSocket服务配置
push-server:
  heartbeat-url-pattern: ws://{host}:{port}/ws/heartbeat/{roomId}?token={token}
  danmaku-url-pattern: ws://{host}:{port}/ws/danmaku/{roomId}?token={token}
  cdn-url-pattern: ws://{host}:{port}/ws/cdn/{roomId}?token={token}

# 令牌配置
barrage:
  token:
    secret: ${TOKEN_SECRET:myBarrageRushSecretKey}
    ttl: ${TOKEN_TTL:3600}
  region:
    default: ${DEFAULT_REGION:cn-east-1}
    available: ${AVAILABLE_REGIONS:cn-east-1,cn-north-1,cn-south-1}
  discovery:
    active-servers-key: ws:active-servers
    server-prefix:
      ws:server:
    refresh-interval: 10000

# 区域配置
geo:
  database:
    path: classpath:GeoLite2-Country.mmdb
# 日志配置
logging:
  level:
    root: INFO
    com.spud.barrage: INFO
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"